"""initial migration

Revision ID: 9f6f9c9d806f
Revises: 
Create Date: 2025-07-27 21:01:06.596104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6f9c9d806f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slot_machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=10), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('slot_machine_id', sa.Integer(), nullable=False),
    sa.Column('start_game', sa.Integer(), nullable=False),
    sa.Column('end_game', sa.Integer(), nullable=False),
    sa.Column('count1', sa.Integer(), nullable=True),
    sa.Column('count2', sa.Integer(), nullable=True),
    sa.Column('count3', sa.Integer(), nullable=True),
    sa.Column('count4', sa.Integer(), nullable=True),
    sa.Column('count5', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['slot_machine_id'], ['slot_machines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('slot_hits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_play_id', sa.Integer(), nullable=False),
    sa.Column('hit_game', sa.Integer(), nullable=False),
    sa.Column('bonus_type', sa.String(length=50), nullable=False),
    sa.Column('flag', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['slot_play_id'], ['slot_plays.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slot_hits')
    op.drop_table('slot_plays')
    op.drop_table('slot_machines')
    # ### end Alembic commands ###
