"""add generic fields to slot_plays

Revision ID: 7a52adeb56c5
Revises: b849778cc5b8
Create Date: 2025-08-04 20:51:26.230596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a52adeb56c5'
down_revision: Union[str, Sequence[str], None] = 'b849778cc5b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_plays', sa.Column('shop_name', sa.String(length=100), nullable=True))
    op.add_column('slot_plays', sa.Column('difference', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_plays', 'difference')
    op.drop_column('slot_plays', 'shop_name')
    # ### end Alembic commands ###
