"""add generic fields to slot_hits

Revision ID: 9d7a87449407
Revises: 
Create Date: 2025-07-28 20:52:18.222646

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d7a87449407'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_hits', sa.Column('count_1', sa.Integer(), nullable=True))
    op.add_column('slot_hits', sa.Column('count_2', sa.Integer(), nullable=True))
    op.add_column('slot_hits', sa.Column('count_3', sa.Integer(), nullable=True))
    op.add_column('slot_hits', sa.Column('count_4', sa.Integer(), nullable=True))
    op.add_column('slot_hits', sa.Column('count_5', sa.Integer(), nullable=True))
    op.add_column('slot_hits', sa.Column('text_1', sa.String(length=255), nullable=True))
    op.add_column('slot_hits', sa.Column('text_2', sa.String(length=255), nullable=True))
    op.add_column('slot_hits', sa.Column('text_3', sa.String(length=255), nullable=True))
    op.add_column('slot_hits', sa.Column('text_4', sa.String(length=255), nullable=True))
    op.add_column('slot_hits', sa.Column('text_5', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_hits', 'text_5')
    op.drop_column('slot_hits', 'text_4')
    op.drop_column('slot_hits', 'text_3')
    op.drop_column('slot_hits', 'text_2')
    op.drop_column('slot_hits', 'text_1')
    op.drop_column('slot_hits', 'count_5')
    op.drop_column('slot_hits', 'count_4')
    op.drop_column('slot_hits', 'count_3')
    op.drop_column('slot_hits', 'count_2')
    op.drop_column('slot_hits', 'count_1')
    # ### end Alembic commands ###
