"""add generic fields to slot_plays

Revision ID: b849778cc5b8
Revises: 9d7a87449407
Create Date: 2025-08-04 20:36:18.579826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b849778cc5b8'
down_revision: Union[str, Sequence[str], None] = '9d7a87449407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('slot_plays', sa.Column('count6', sa.Integer(), nullable=True))
    op.add_column('slot_plays', sa.Column('count7', sa.Integer(), nullable=True))
    op.add_column('slot_plays', sa.Column('count8', sa.Integer(), nullable=True))
    op.add_column('slot_plays', sa.Column('count9', sa.Integer(), nullable=True))
    op.add_column('slot_plays', sa.Column('count10', sa.Integer(), nullable=True))
    op.add_column('slot_plays', sa.Column('text_1', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_2', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_3', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_4', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_5', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_6', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_7', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_8', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_9', sa.String(length=255), nullable=True))
    op.add_column('slot_plays', sa.Column('text_10', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('slot_plays', 'text_10')
    op.drop_column('slot_plays', 'text_9')
    op.drop_column('slot_plays', 'text_8')
    op.drop_column('slot_plays', 'text_7')
    op.drop_column('slot_plays', 'text_6')
    op.drop_column('slot_plays', 'text_5')
    op.drop_column('slot_plays', 'text_4')
    op.drop_column('slot_plays', 'text_3')
    op.drop_column('slot_plays', 'text_2')
    op.drop_column('slot_plays', 'text_1')
    op.drop_column('slot_plays', 'count10')
    op.drop_column('slot_plays', 'count9')
    op.drop_column('slot_plays', 'count8')
    op.drop_column('slot_plays', 'count7')
    op.drop_column('slot_plays', 'count6')
    # ### end Alembic commands ###
